# Generated by Django 3.2.3 on 2021-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('contents', models.TextField(max_length=255, verbose_name='contents')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
    ]
